docs:
  - name: AI资讯
    id: KvLado1XOoMDz3x4Ssncj6QAnrb
  - name: AI开源
    id: ZG0KdjxWaoqCOFxXZU8cJygQn4d
  - name: AI产品
    id: XZm7dlNOIoL3i1xEXojcW5VfnBb
  - name: 赚钱商机
    id: VBVCdrpiOoPuLbxNLiMcJh8Unvd
  - name: 独立开发
    id: UzRAdpN4NohoXMxU2Mhcr6PZngb
  - name: 其他内容
    id: HugFd6gpHopDpCxpCI7caXqQnkZ