wiki:
  id: FZp8wvXhuiu9YtkmAgfcAuVEnRe
  items:
    - name: 人工智能
      id: Fyk0wohUMi01MwksjZ0cqRcinYb
    - name: 独立开发
      id: G9YXwjZMni6ZY1kIei5cXwvxnEc
    - name: 编程技术
      id: VoD1wHJk6iIW7tkRpEjcUBf5nYe
    - name: 赚钱商机
      id: UFGrwaaKhimBrIkBdsJcCaRbn7d
    - name: 人生杂谈
      id: MkqUwNifsipd07k8phic6Azsncd
    - name: 其他内容
      id: ZZw3w73esiGifAkGYXscMuXNnIb